### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [2]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [5]:
np.random.rand(2, 3) # 0에서 1사이의 unifrom distribution

array([[0.87749319, 0.02712112, 0.43277006],
       [0.98881747, 0.81941873, 0.63709495]])

In [6]:
np.random.rand(5, 4, 3)

array([[[0.33429962, 0.97532752, 0.4661347 ],
        [0.16765044, 0.01068081, 0.62051294],
        [0.44167982, 0.2612058 , 0.04398813],
        [0.24920499, 0.33550856, 0.59435937]],

       [[0.27995829, 0.32554211, 0.4267093 ],
        [0.02354452, 0.94234449, 0.15625512],
        [0.07445451, 0.33607476, 0.16704709],
        [0.01250651, 0.26463424, 0.00492307]],

       [[0.76952484, 0.44207744, 0.02267043],
        [0.19845888, 0.49657668, 0.05682062],
        [0.62512434, 0.28113044, 0.84223446],
        [0.14036188, 0.20704697, 0.40224839]],

       [[0.5456115 , 0.60199549, 0.59980501],
        [0.63722515, 0.52841216, 0.66129034],
        [0.94942529, 0.61602681, 0.03234256],
        [0.76425047, 0.70665989, 0.24703209]],

       [[0.77321499, 0.29157459, 0.24633155],
        [0.99544457, 0.18833476, 0.8594111 ],
        [0.18730366, 0.06122533, 0.28498654],
        [0.25972977, 0.3220616 , 0.97452931]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [8]:
np.random.randn(5) # random normal distribution

array([-1.40090468, -0.27620023,  1.91261056, -0.04443519, -1.351647  ])

In [9]:
np.random.randn(3, 4)

array([[ 0.88953193, -0.2406161 , -0.04352653,  0.29180881],
       [ 0.62183736,  0.28682973,  1.06712872,  0.33780945],
       [ 2.19881192,  0.38729717,  1.55099881,  0.88997125]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [13]:
np.random.randint(1, 100, size=(3, 5, 2))

array([[[ 5, 19],
        [92, 72],
        [80, 83],
        [52, 15],
        [36, 42]],

       [[65, 39],
        [64, 26],
        [21, 96],
        [16, 50],
        [19, 57]],

       [[98, 65],
        [39, 78],
        [98, 12],
        [89,  4],
        [66, 65]]])

In [14]:
np.random.randint(1, 100, size=(5,))

array([66, 59, 24, 35, 76])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [20]:
np.random.seed(100)

In [25]:
np.random.seed(20)
np.random.randn(3, 4)

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [26]:
np.random.choice(100, (3, 4))

array([[58, 25,  3, 74],
       [75, 61, 77, 83],
       [57, 94, 32, 10]])

In [27]:
x = np.array([1, 2, 3, 5, 2.3, 5.4, 3.1])
np.random.choice(x, size=(2, 2))

array([[5. , 3.1],
       [5. , 3. ]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [28]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[1.5059482 , 2.74839351, 1.57772338, 1.6389199 , 2.15187649],
       [2.61607297, 1.48296955, 2.66982336, 2.49426389, 1.88261977],
       [1.17810339, 1.7666985 , 1.83610823, 2.52994467, 1.39855603],
       [1.09808429, 2.34808332, 1.03964067, 2.59313215, 2.43101907]])

In [29]:
np.random.normal(size=(3, 4))

array([[-1.01687734, -1.21580898, -0.64920115, -0.41416863],
       [ 0.28375927, -0.09503477, -0.09700659, -0.14962102],
       [ 2.00500464, -2.08473468,  1.25170782, -1.02567366]])