### 학습목표
 1. 인덱싱과 슬라이싱 활용하기


In [2]:
import numpy as np

#### 인덱싱
 - 파이썬 리스트와 동일한 개념으로 사용
 - ,를 사용하여 각 차원의 인덱스에 접근 가능

 * 1차원 벡터 인덱싱

In [3]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
# get first element
x[0]
# get last element
x[-1]
# get third element
x[2]

2

* 2차원 행렬 인덱싱

In [7]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
# get 0 row
x[0]
# get 0 row and 2 col cell
x[0, 2]
# get all 3 col
x[:, 2]

array([2, 7])

* 3차원 텐서 인덱싱

In [13]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [16]:
x[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
x[1, 2]

array([18, 19, 20])

In [22]:
x[2, 1, 0]

27

#### 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능

* 1차원 벡터 슬라이싱

In [23]:
x = np.arange(10)

In [26]:
x[1:8]

array([[5, 6, 7, 8, 9]])

In [27]:
x[1:]

array([[5, 6, 7, 8, 9]])

* 2차원 행렬 슬라이싱

In [25]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [30]:
# [[1,2,3], [6,7,8]]
x[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [34]:
# [[0,1], [5,6]]
x[:, :2]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[24, 25, 26],
        [27, 28, 29]]])

In [36]:
print(x[0, 2])
print(x[:1, 2]) # slicing preserve dimension

[6 7 8]
[[6 7 8]]


* 3차원 텐서 슬라이싱

In [37]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [40]:
# [[[0,1,2],[3,4,5]]]
x[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [41]:
x[0, :2, :]

array([[0, 1, 2],
       [3, 4, 5]])