<a href="https://colab.research.google.com/github/kwanhong66/TodayILearned/blob/master/python_ml_complete_guide/2%EC%9E%A5/2_2_%EC%B2%AB_%EB%B2%88%EC%A7%B8_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EB%A7%8C%EB%93%A4%EC%96%B4_%EB%B3%B4%EA%B8%B0_%EB%B6%93%EA%BD%83_%ED%92%88%EC%A2%85_%EC%98%88%EC%B8%A1%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Book] 파이썬 머신러닝 완벽 가이드
- 예제 코드 transcription
- 개념, 프로세스, API, Best Practice 등 익히기
- 책 예제 코드 github (https://github.com/wikibook/pymldg-rev)

## 2.2 첫 번째 머신러닝 만들어보기 - 붓꽃 품종 예측하기

- Scikit-learn으로 첫 번째로 만들어보는 머신러닝 모델
- 붓꽃(Iris) 데이터 셋으로 붓꽃의 품종을 분류하는 문제
- 꽃잎의 길이와 너비, 꽃받침의 길이와 너비 feature로 품종 예측

In [0]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

- load_iris() 함수로 iris dataset를 로드
- DataFrame으로 구성하여 확인

In [5]:
import pandas as pd

# Load iris dataset
iris = load_iris()

# iris.data is numpy array which has feature values
iris_data = iris.data
print(iris_data.shape)
print(iris_data)

# iris.target is numpy which has target values
iris_label = iris.target
print('iris target 값:', iris_label)
print('iris target 명:', iris.target_names)

# Convert iris dataset into DataFrame
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

(150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  label
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0

[3 rows x 5 columns]

- train_test_split() 메소드로 학습 데이터와 테스트 데이터 분리
- feature data, label data, test_size, random_state

In [0]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,
                                                    test_size=0.2, random_state=1)

- Decision Tree를 이용한 분류 모델 (DeicisionTreeClassifier)
- random_state 값으로 동일한 학습/예측 결과 출력
- fit() 메소드를 호출하여 학습

In [0]:
# Create DecisionTreeClassifier
dt_clf = DecisionTreeClassifier(random_state=11)

In [8]:
# Run training
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=11, splitter='best')

- 분류 모델의 predict() 메소드를 사용하여, test feature 데이터에 대하여 label 예측

In [0]:
# Run prediction with trained DecisionTreeClassifier
pred = dt_clf.predict(X_test)

- accuracy_score() 메소드로 예측값과 정답을 이용하여 정확도(accuracy) 계산

In [12]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9667


1. **데이터 세트 분리**: 데이터를 학습/테스트 셋으로 분리하여, 학습과 테스트를 별개의 셋으로 진행
2. **모델 학습**: 학습 데이터를 ML 알고리즘으로 모델 학습
3. **예측 수행**: 앞선 단계에서 학습된 모델로 테스트 데이터에 대하여 예측
4. **평가**: 학습 모델로 예측한 결과값과 실제 정답을 비교하여 모델의 성능 평가 