## 학습목표

* Tensorflow 2.0 간단 사용법

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
tf.__version__

'2.3.0'

## Tensor 생성

* List 생성

In [4]:
[1, 2, 3]

[1, 2, 3]

In [5]:
[[1, 2, 3], [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

### Array 생성

* tuple과 list 모두 np.array로 array 생

In [9]:
arr = np.array([1, 2, 3])

In [10]:
arr.shape

(3,)

In [11]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

In [12]:
arr.shape

(2, 3)

### Tensor 생성

* tf.constant()
  - list -> Tensor

In [13]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

* tf.constant()
  - tuple -> Tensor

In [14]:
tf.constant(((1, 2, 3), (1, 2, 3)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

* tf.constant()
  - Array -> Tensor

In [15]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [17]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

## Tensor에 담긴 정보 확인

* shape 확인

In [18]:
tensor.shape

TensorShape([3])

* data type 확인
  - Tensor 생성 시에 data type을 정해주지 않음 (Python)

In [19]:
tensor.dtype

tf.int64

* data type 정의

In [21]:
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

* data type 변환
  - Numpy의 astype, TF의 cast

In [22]:
arr = np.array([1, 2, 3], dtype=np.float32)

In [24]:
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [25]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [26]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

* Tensor에서 Numpy 불러오기
  - numpy()

In [27]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

* np.array()

In [28]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

* numpy array 변환 확인

In [29]:
type(tensor.numpy())

numpy.ndarray

## 난수 생성

* Normal distribution and Uniform distribution
  - Normal distribution: 중심극한 이론; 연속적인 모양 (bell shape)
  - Uniform distribution: 불연속적이고 일정한 분포

* numpy의 normal distribution
  - np.random.randn()

In [30]:
np.random.randn(9)

array([-0.03167786,  0.6397765 , -1.73497897, -0.01849869,  0.14135746,
       -1.61715171,  1.85840834, -0.22574316, -0.3719733 ])

In [34]:
tf.random.normal([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.3280356 ,  1.2700068 , -0.1826586 ],
       [-0.06749205,  2.1148849 , -0.63306963],
       [-1.7840568 , -0.3243404 ,  1.1606886 ]], dtype=float32)>

In [36]:
tf.random.uniform([4, 4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.78724635, 0.04956639, 0.7236872 , 0.80739033],
       [0.26179278, 0.761749  , 0.88951087, 0.6233188 ],
       [0.21134698, 0.25351775, 0.10615158, 0.50895953],
       [0.92265034, 0.22796929, 0.58033085, 0.67220783]], dtype=float32)>