## PyTorch Basic

PyTorch 기초 사용법

In [1]:
import numpy as np
import torch

In [2]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
nums.shape

torch.Size([9])

In [5]:
type(nums)

torch.Tensor

In [6]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
nums.reshape([3, 3])

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
random = torch.rand([3, 3])
random

tensor([[0.0169, 0.7165, 0.5968],
        [0.5046, 0.6148, 0.2083],
        [0.4260, 0.1880, 0.5501]])

In [10]:
zeros = torch.zeros([3, 3])
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
ones = torch.ones([3, 3])
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
zeros.size()

torch.Size([3, 3])

## Operations

PyTorch로 수학연산

In [14]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [15]:
nums = nums.reshape([3, 3])

In [16]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [18]:
result = torch.add(nums, 3)

In [19]:
result.numpy()

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## View

In [20]:
range_nums = torch.arange(9).reshape(3, 3)

In [22]:
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [23]:
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
range_nums.view(1, 9)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

## Slice and Index

In [25]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [26]:
nums[1]

tensor([3, 4, 5])

In [28]:
nums[1, 1]

tensor(4)

In [29]:
nums[1:, 1:]

tensor([[4, 5],
        [7, 8]])

In [30]:
nums[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

## Compile

numpy를 torch tensor로 불러오기

In [31]:
arr = np.array([1, 1, 1])

In [32]:
arr_torch = torch.from_numpy(arr)

In [33]:
arr_torch.float()

tensor([1., 1., 1.])

In [34]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [36]:
arr_torch.to(device)

tensor([1, 1, 1])

In [37]:
device

'cpu'

## AutoGrad

In [40]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [41]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [42]:
y.grad_fn

In [43]:
z = y * y * 3
out = z.mean()

In [44]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [45]:
out.backward()

In [46]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [48]:
x.requires_grad
(x ** 2).requires_grad

True

In [50]:
with torch.no_grad():
  print((x ** 2).requires_grad)

False
